### ISSUE TITLE
High mouse sensitivity in the main menu

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#1]
For the game, the sensitivity can be adjusted for yourself, but for the main menu it cannot be done.
For me personally, the mouse moves quickly in the menu, which is why I have to slowly control it in order to select the desired menu item.

**Comment by zturtleman** [comment]
This should be fixed by 2b93e6752762442f56087d3f5d7d1309bf0b7c34.

**Comment by zturtleman** [comment]
Never mind. I reverted it in efd3a95e9a89c7577793607b87f8f4e202211463.

Originally the mouse cursor moved faster in the in-game menu than out of game (regular desktop usage).

Testing this patch with `in_nograb 1` (to display system cursor in menu) on Linux in windowed mode the mouse sensitivity matches that of regular out of game movement. (Great!)

However testing this patch with `in_nograb 0` (the default) the in-game cursor is now notably slower than moving the mouse cursor out of game (Unacceptable!) which is why I didn't merge this into ioquake3 years ago.

I have another idea though.

**Comment by insellium** [comment]
What's the idea?

**Comment by zturtleman** [comment]
Use absolute mouse input to emulate relative input while in the menu.
